### ISSUE TITLE
Freezing on "word-by-word" 

### ISSUE THREAD

**Issue by outscrape** [robbiebarrat/rapping-neural-network#8] opened 2017-03-20 23:33 UTC
Using the following info I'm getting no progression (waited several hours) on a 300kb lyrics.txt file. Line by line works fine.

training = 0 
epoch = 100
word_by_word = 1 

Any suggestions on changes I could make?

**Comment by robbiebarrat** [comment] 2017-03-20 23:49
Upload the lyrics file so I can see what the issue is - I know it has to do with the Markov chain, but once you send me the lyrics I'll be able to make an appropriate bugfix. Sorry for the inconvenience.

**Comment by robbiebarrat** [comment] 2017-03-21 03:55
Just updated deeprap.py - issue was with the Markov chain building a text model. It wasn't getting the newline delimits correctly - fixed now though. Sorry again!

**Closed by robbiebarrat** 2017-03-21 03:55 UTC
